"""add mpesa fields to payment

Revision ID: 46380777ff14
Revises: 711c28d5ec14
Create Date: 2026-03-18 23:16:54.354829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46380777ff14'
down_revision = '711c28d5ec14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'completed'), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
