"""add mpesa fields

Revision ID: 57d69a042801
Revises: 46380777ff14
Create Date: 2026-04-02 06:28:13.878230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d69a042801'
down_revision = '46380777ff14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('mpesa_receipt')

    # ### end Alembic commands ###
